### ISSUE TITLE
Design OneLogOn Landing Page

### ISSUE THREAD

**Issue by cipriane** [cipriane/OneLogOn#58]
Design the layout & content of the landing page for the frontend people to reference and create a proper webpage.

Website visitors should be able to log in, register, view a gallery, and perhaps view a live demo.

If a website visitor is already signed in, they should be redirected to their dashboard.

Designs #55

**Comment by cipriane** [comment]
Design available here: https://docs.google.com/document/d/1p8r_iqelGkeo1wjg6oP9eB4-leLYqUKjB_UtHoFWV4k/edit

**Comment by cipriane** [comment]
@skarchmit I updated the design document a bit, added a Version 2. Not much has significantly changed, but I incorporated Victor's suggestion to move the elements around a bit.

**Comment by skarchmit** [comment]
Is this done already? Or will it only be complete at the very end? This is the design part of it.

**Comment by cipriane** [comment]
I think we can say this is done.
